version: '3.5'
services:
  web:
    tty: true
    stdin_open: true
    container_name: blockchain_web
    image: hodai.lake/blockchain-python:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    
  redis:
    image: redis:5.0-alpine

  proxy:
    image: traefik:v2.0
    network_mode: host
    ports:
      - "6000:80"
      - "433:433"
      - "8080:8080"
    volumes:
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml # Traefik static config
      - ${PWD}/traefik.config.toml:/etc/traefik/traefik.config.toml # Traefik dynamic config
      - ${PWD}/devcerts:/etc/certs # SSL Development Certificate