[http]
  [http.routers]
    [http.routers.http-to-my-app]
      # You can change the rules here and make it more complex. Check traefik
      # docs!
      rule = "Host(`lake-blockchain.com`)"
      service = "lake-blockchain"
      entrypoints = ["http"]
      middlewares = ["redirect"]

    [http.routers.https-to-lake-blockchain]
      rule = "Host(`lake-blockchain.com`)"
      service = "lake-blockchain"
      entrypoints = ["https"]
      [http.routers.https-to-lake-blockchain.tls]

  [http.services]
    [http.services.lake-blockchain]
      [http.services.lake-blockchain.loadBalancer]
       passHostHeader = true

        [[http.services.lake-blockchain.loadBalancer.servers]]
          # This is where your dev app lives.
          url = "http://127.0.0.1:5000/"

  [http.middlewares]
    [http.middlewares.redirect.redirectScheme]
      scheme = "https"

[tls]
  [[tls.certificates]]
    certFile = "/etc/certs/lake-blockchain.com+1.pem"
    keyFile = "/etc/certs/lake-blockchain.com+1-key.pem"